export const SEARCH_SEARCH_MOVIES_ERROR = 'SEARCH_SEARCH_MOVIES_ERROR';
export const SEARCH_SEARCH_MOVIES_SUCCESS = 'SEARCH_SEARCH_MOVIES_SUCCESS';
export const SEARCH_SEARCH_MOVIES_LOADING = 'SEARCH_SEARCH_MOVIES_LOADING';
